# Generated by Django 3.0 on 2020-01-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_type', models.CharField(max_length=100)),
                ('creator_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('theory_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=250)),
                ('task', models.CharField(max_length=1000)),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Theory')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryGraphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic', models.ImageField(upload_to='graphics')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Theory')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Theory')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='email address')),
                ('password', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=25)),
                ('person_type', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
