# Generated by Django 3.0 on 2020-01-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='theoryformula',
            name='theory',
        ),
        migrations.RemoveField(
            model_name='theorygraphic',
            name='theory',
        ),
        migrations.RemoveField(
            model_name='theorytask',
            name='theory',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Theory',
        ),
        migrations.DeleteModel(
            name='TheoryFormula',
        ),
        migrations.DeleteModel(
            name='TheoryGraphic',
        ),
        migrations.DeleteModel(
            name='TheoryTask',
        ),
    ]
