# Generated by Django 3.0 on 2020-01-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200118_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_type', models.CharField(max_length=100)),
                ('creator_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('theory_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=250)),
                ('task', models.CharField(max_length=1000)),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Theory')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryGraphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic', models.ImageField(upload_to='graphics')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Theory')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Theory')),
            ],
        ),
    ]
