# Generated by Django 3.0 on 2020-01-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_theory_theoryformula_theorygraphic_theorytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
    ]
