# Generated by Django 3.0 on 2020-01-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200118_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorytask',
            name='theory',
            field=models.CharField(max_length=100),
        ),
    ]
