# Generated by Django 3.0 on 2020-01-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200118_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorygraphic',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theoryformula',
            name='theory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='theorygraphic',
            name='theory',
            field=models.CharField(max_length=100),
        ),
    ]
