# Generated by Django 3.0 on 2020-01-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200119_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theoryformula',
            name='theory',
        ),
        migrations.RemoveField(
            model_name='theorygraphic',
            name='theory',
        ),
        migrations.RemoveField(
            model_name='theorytask',
            name='theory',
        ),
        migrations.AddField(
            model_name='theory',
            name='creator_email',
            field=models.CharField(default='askhat.kenenbay@nu.edu.kz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryformula',
            name='course_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryformula',
            name='creator_email',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryformula',
            name='footer',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryformula',
            name='header',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryformula',
            name='main',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryformula',
            name='theory_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorygraphic',
            name='course_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorygraphic',
            name='creator_email',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorygraphic',
            name='theory_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorytask',
            name='course_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorytask',
            name='creator_email',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorytask',
            name='theory_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
