# Generated by Django 3.0 on 2020-01-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200119_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_email', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('theory_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('more', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='theoryformula',
            name='category',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
