# Generated by Django 3.0 on 2020-01-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_coursetaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetaken',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
