# Generated by Django 3.0 on 2020-01-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_coursetaken_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_god',
            field=models.BooleanField(default=False),
        ),
    ]
