# Generated by Django 3.0 on 2020-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_person_is_god'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_email', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('homework_name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_email', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('homework_name', models.CharField(max_length=100)),
                ('points', models.CharField(max_length=250)),
            ],
        ),
    ]
