# Generated by Django 3.0 on 2020-01-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_homework_homeworkpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='text',
            field=models.TextField(),
        ),
    ]
