# Generated by Django 3.0 on 2020-01-29 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200129_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
    ]
