# Generated by Django 3.0 on 2020-01-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200129_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
    ]
