# Generated by Django 3.0 on 2020-01-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200129_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
