# Generated by Django 3.0 on 2020-01-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_homework_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='creator_email',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
