# Generated by Django 3.0 on 2020-02-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_surveystudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveystudent',
            name='email',
            field=models.CharField(default='empty', max_length=250),
        ),
    ]
