# Generated by Django 3.0 on 2020-03-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200210_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerOne', models.IntegerField()),
                ('answerOneText', models.CharField(default='empty', max_length=250)),
                ('answerTwo', models.IntegerField()),
                ('answerTwoText', models.CharField(default='empty', max_length=250)),
                ('answerThree', models.IntegerField()),
                ('answerThreeText', models.CharField(default='empty', max_length=250)),
                ('answerFourText', models.CharField(default='empty', max_length=250)),
                ('answerFiveText', models.CharField(default='empty', max_length=250)),
            ],
        ),
    ]
