# Generated by Django 3.0 on 2020-03-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveystudent',
            name='client_name',
        ),
        migrations.AddField(
            model_name='surveystudent',
            name='fio',
            field=models.CharField(default='empty', max_length=250),
        ),
        migrations.AddField(
            model_name='surveystudent',
            name='language',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveystudent',
            name='phone',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveystudent',
            name='when',
            field=models.CharField(default='asd', max_length=500),
            preserve_default=False,
        ),
    ]
