# Generated by Django 3.0 on 2020-03-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200307_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='empty', max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='surveytutor',
            name='date',
        ),
        migrations.RemoveField(
            model_name='surveytutor',
            name='money',
        ),
        migrations.RemoveField(
            model_name='surveytutor',
            name='rec',
        ),
        migrations.AddField(
            model_name='surveytutor',
            name='experience',
            field=models.CharField(default='empty', max_length=250),
        ),
        migrations.AddField(
            model_name='surveytutor',
            name='price',
            field=models.CharField(default='empty', max_length=250),
        ),
        migrations.AddField(
            model_name='surveytutor',
            name='subjects',
            field=models.CharField(default='empty', max_length=250),
        ),
        migrations.AddField(
            model_name='surveytutor',
            name='time',
            field=models.CharField(default='empty', max_length=250),
        ),
        migrations.AddField(
            model_name='surveytutor',
            name='university',
            field=models.CharField(default='empty', max_length=250),
        ),
    ]
